// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Userid   string `json:"userid"`
	Password string `json:"password"`
}

type UserRegisterReply struct {
}

type UserLoginRequest struct {
	Userid   string `json:"userid"`
	Password string `json:"password"`
}

type UserLoginReply struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserPasswordModifyRequest struct {
	Userid      string `json:"userid"`
	OldPassword string `json:"oldpassword"`
	NewPassword string `json:"newpassword"`
}

type UserPasswordModifyReply struct {
}

type UserCancleRequest struct {
	Userid   string `json:"userid"`
	Password string `json:"password"`
}

type UserCancleReply struct {
}
